### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tatacsd** [tatacsd/Product-Unit-Cost-Application-Project#83]
- [x] invoice details refresh the page after adding an item
- [x] add droplist for the ids of invoice details
- [x] changing home to have dashboard instead of signup
- [x] invoices display a dropwon for suppliers
- [ ]
